Privatix/dapp-openvpn

.codeclimate.yml
common/dappctrl/connector/connector.go
common/logger/logger.go

Added interfaces that should be implemented.

---

Gopkg.toml
installer/main.go
installer/proc.go

Move application version from dappctrl.

---

adapter/config/config.go
adapter/data/offering.go
adapter/main.go
adapter/tc/errors.go
adapter/tc/tc.go
adapter/tc/tc_darwin.go
adapter/tc/tc_linux.go
adapter/tc/tc_windows.go
scripts/run_adapter.sh

Move TC package from dappctrl

---

adapter/config/config.go
adapter/main.go

Make the client adapter to run as service

---

inst/command/funcs.go
inst/docs/config.md
inst/openvpn/execute.go
inst/openvpn/misc.go
inst/openvpn/openvpn.go

fix creating openvpn config

---

inst/command/command.go
inst/command/const.go
inst/command/funcs.go
inst/openvpn/dappvpn.go
inst/openvpn/execute.go
inst/openvpn/misc.go
inst/openvpn/misc_darwin.go
inst/openvpn/misc_linux.go
inst/openvpn/misc_windows.go
inst/openvpn/openvpn.go
inst/openvpn/path/path.go

dappvpn starts as service

---

adapter/config/config.go
adapter/main.go
adapter/msg/config.go
adapter/msg/config_test.go
adapter/msg/msg_test.go
adapter/prepare/prepare.go
files/example/dappvpn.agent.config.json
files/example/dappvpn.client.config.json
files/test/test.conf
statik/ovpn/templates/client-config.tpl

Add `dev-node` argument to client openvpn config.

---

.github/CODEOWNERS
installer/README.md

add readme.md

---

inst/README.md
inst/command/command.go
inst/command/funcs.go
inst/main.go
inst/openvpn/misc.go
inst/openvpn/openvpn.go

1. Displays version.
2. Resolves BV-1186.

fix BV-1186

---

inst/openvpn/openvpn.go

runs set-nat.ps1 only on agent

---

inst/command/funcs.go
inst/env/env.go
inst/openvpn/dappvpn.go
inst/openvpn/tap.go
statik/ovpn/templates/client-config.tpl
statik/ovpn/templates/server-config.tpl

sets GUID to dev-node

---

scripts/win/new-startupTask.ps1
scripts/win/reenable-nat.ps1

- new-startupTask.ps1 -> creates scheduled task that runs reenable-nat.ps1 on system startup
- reenable-nat.ps1 ->  re-enable ICS and restart Privatix OpenVPN server service

Re-enable ICS on startup

---

inst/command/command.go
inst/command/funcs.go
inst/openvpn/misc.go
inst/openvpn/openvpn.go
inst/openvpn/path/path.go

creates schedule task and restart after install

---

adapter/main.go
adapter/misc.go

Recover channel state after crash

---

inst/command/funcs.go

dappvpn auto restart

---

adapter/config/config.go
adapter/main.go
adapter/mon/monitor_test.go
adapter/msg/msg_test.go
adapter/msg/pusher.go
adapter/msg/pusher_test.go
adapter/prepare/prepare.go
adapter/prepare/prepare_test.go
files/example/dappvpn.agent.config.json
files/example/dappvpn.client.config.json
inst/openvpn/dappvpn.go
inst/openvpn/misc.go
installer/proc.go
statik/package/config/adapter.config.json

Rewrite the session server to support RPC

---

adapter/msg/config.go
adapter/msg/config_test.go
adapter/prepare/prepare.go
adapter/prepare/prepare_test.go
statik/ovpn/templates/client-config.tpl

Enable logging for client.ovpn

---

Gopkg.toml
adapter/main.go
adapter/misc.go

remove heartbeat, use subscription to connection change instead

---

Gopkg.toml.template
adapter/config/config.go
adapter/main.go
adapter/msg/pusher.go
adapter/msg/pusher_test.go

Added UPnP and NAT-PMP mechanisms for opening external port on a router for openvpn server.

Add NAT traversal

---

files/example/templates/offering.json
statik/package/template/template.access.json
statik/package/template/template.offering.json
statik/product/product.agent.json
statik/product/product.client.json

Hash must be Hex of `Keccak256` from template's raw field

fix tpl hash

---

adapter/main.go
adapter/misc.go
adapter/msg/config.go

Uses `sess.Client` from here Privatix/dappctrl#437

refactor to sess.Client

---

inst/command/const.go
statik/package/template/template.access.json
statik/package/template/template.offering.json
statik/product/product.agent.json
statik/product/product.client.json

remove calculated and redundant fields

---

.travis.yml
Gopkg.toml.template
README.md
adapter/mon/monitor.go
adapter/mon/monitor_test.go
go.mod
go.sum
scripts/run_tests.sh

I've skipped all tests in `adapter/mon`.
@furkhat please fix it according to the https://github.com/Privatix/privatix/issues/127

add travis

---

scripts/win/set-nat.ps1

- fix potential bug
- fix help not displayed get-help -full
- fix text typos

fix already shared error case

---

inst/openvpn/tap.go

fix installation tap device on korean/japanese windows

---

scripts/linux/nat-pf.sh
scripts/mac/nat-pf.sh

Added firewall rules to block access from vpn to lan

FW block from openvpn net to LAN (mac,linux)

---

inst/openvpn/misc.go
scripts/win/reenable-nat.ps1
scripts/win/set-nat.ps1

* script refactoring
* noted, that sometimes remoteAccess service requires restart to handle changes
* `-Force` flag introduced to force resetting ICS settings before set

windows set NAT (ICS) more aggressively
